"""Initial schema setup

Revision ID: a88910c7918e
Revises: 
Create Date: 2026-06-28 19:54:51.820437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88910c7918e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS feature_store")
    op.execute("CREATE SCHEMA IF NOT EXISTS fundamental")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futures_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('root', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contract_size', sa.Integer(), nullable=False),
    sa.Column('settlement', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('margin_requirement', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_futures_contracts_root'), 'futures_contracts', ['root'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_futures_contracts_symbol'), 'futures_contracts', ['symbol'], unique=True, schema='auth')
    op.create_table('option_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('last', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('implied_volatility', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('gamma', sa.Float(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('vega', sa.Float(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_option_contracts_symbol'), 'option_contracts', ['symbol'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_option_contracts_underlying'), 'option_contracts', ['underlying'], unique=False, schema='auth')
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True, schema='auth')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_table('fundamental_features',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('time', 'ticker'),
    schema='feature_store'
    )
    op.create_table('market_features',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('returns_1d', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('returns_5d', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('returns_20d', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('realized_vol_20', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('market_beta', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('spy_correlation', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('qqq_correlation', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('time', 'ticker'),
    schema='feature_store'
    )
    op.create_table('sentiment_features',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('sentiment_mean', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('time', 'ticker'),
    schema='feature_store'
    )
    op.create_table('technical_features',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('atr', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bollinger_width', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_10', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_200', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('time', 'ticker'),
    schema='feature_store'
    )
    op.create_table('financial_statements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('fiscal_period', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('shares_outstanding', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='fundamental'
    )
    op.create_index(op.f('ix_fundamental_financial_statements_ticker'), 'financial_statements', ['ticker'], unique=False, schema='fundamental')
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_refresh_token'), table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index(op.f('ix_fundamental_financial_statements_ticker'), table_name='financial_statements', schema='fundamental')
    op.drop_table('financial_statements', schema='fundamental')
    op.drop_table('technical_features', schema='feature_store')
    op.drop_table('sentiment_features', schema='feature_store')
    op.drop_table('market_features', schema='feature_store')
    op.drop_table('fundamental_features', schema='feature_store')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_index(op.f('ix_auth_revoked_tokens_token'), table_name='revoked_tokens', schema='auth')
    op.drop_table('revoked_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_option_contracts_underlying'), table_name='option_contracts', schema='auth')
    op.drop_index(op.f('ix_auth_option_contracts_symbol'), table_name='option_contracts', schema='auth')
    op.drop_table('option_contracts', schema='auth')
    op.drop_index(op.f('ix_auth_futures_contracts_symbol'), table_name='futures_contracts', schema='auth')
    op.drop_index(op.f('ix_auth_futures_contracts_root'), table_name='futures_contracts', schema='auth')
    op.drop_table('futures_contracts', schema='auth')
    # ### end Alembic commands ###
